# Generated by Django 2.2.20 on 2021-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(choices=[(True, 'да'), (False, 'нет'), (None, 'Неизвестно')], verbose_name='Новое здание'),
        ),
    ]
