# Generated by Django 2.2.20 on 2021-10-08 14:01

from django.db import migrations


def get_new_buildings(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
            flat.save()
        elif flat.construction_year < 2015:
            flat.new_building = False
            flat.save()
        else:
            flat.new_building = None
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(get_new_buildings)
    ]
