# Generated by Django 2.2.20 on 2021-10-15 14:08

from django.db import migrations


def link_flats_with_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        flat = Flat.objects.filter(owner=owner.owner)
        owner.flats.set(list(flat))


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20211014_1747'),
    ]

    operations = [
        migrations.RunPython(link_flats_with_owners)
    ]
